name: Dependabot Automation
on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches:
      - "dependabot/**"

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    name: Try to auto-merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Dependabot auto-merge
        uses: fastify/github-action-merge-dependabot@v3.0.2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
